name: psf_srdn
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy=1.24.*
  - pandas=1.4.*
  - matplotlib=3.7.*
  - pillow=10.*
  - scikit-image=0.18.*
  - scikit-learn=1.0.*
  - scipy=1.10.*
  - seaborn=0.11.*
  - pytorch=1.12.0
  - torchvision=0.13.0
  - torchaudio=0.12.0
  - tqdm
  - pip
  - pip:
      - einops==0.6.0
      - torchmetrics @ file:///home/conda/feedstock_root/build_artifacts/torchmetrics_1651830953557/work
