name: psf_srdn
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - numpy=1.24.4
  - pandas=1.4.0
  - matplotlib=3.7.0
  - pillow=10.3.0
  - scikit-image=0.18.3
  - scikit-learn=1.0.2
  - scipy=1.10.1
  - seaborn=0.11.2
  - tqdm=4.65.0
  - pip:
      - einops==0.6.0
      - torch==1.12.0+cu113   # or install torch separately (see below)
      - torchvision==0.13.0+cu113
      - torchaudio==0.12.0+cu113
      - --extra-index-url https://download.pytorch.org/whl/cu113
      - torchmetrics  # if needed
