name: psf_srdn
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - numpy=1.24.4
  - pandas=1.4.0
  - matplotlib=3.7.0
  - pillow=10.3.0
  - scikit-image=0.18.3
  - scikit-learn=1.0.2
  - scipy=1.10.1
  - seaborn=0.11.2
  - tqdm=4.65.0
  - pip:
      - torch==2.1.0
      - torchaudio==2.1.0
      - torchvision==0.16.0
      - einops==0.6.0
      - torchmetrics==0.9.3
      - opencv-python==4.9.0.80
